config/routes.rb
Rails.application.routes.draw do
  get 'menu_categories/index'
  get 'menu_categories/show'
  get 'menu_categories/edit'
  patch 'menu_categories/update'
  get 'menu_categories/delete'



resources :menu_items
  # get 'menu_items/index'
  # get 'menu_items/show'
  # get 'menu_items/edit'
  # get 'menu_items/update'
  # get 'menu_items/delete'

  devise_for :users

  root 'orders#index'

# - - - - - - - - USERS has_many Addresses/Phone Numbers/Orders

  # resources :users, only: [:show, :create, :update, :edit] do
  #   resources :addresses
  #   resources :phone_numbers
  #   resources :orders, only: [:index, :show, :create, :delete]
  # end

  get 'orders/index', to: "orders#index"
  get 'orders/show', to: "orders#show"
  post 'orders/create', to: "orders#create"
  get 'orders/edit', to: "orders#edit"
  get 'orders/delete', to: "orders#delete"



  # patch 'menus/update', to: "menus#update"

resources :menus do
  resources :menu_items
end

  # get 'menus/index' => 'menus'
  # get 'menus/new', to: 'menus#new'
  # post 'menus/create', to:'menus#create'
  # get 'menus/:id', to: 'menus#show'
  # get 'menus/:id/edit', to: 'menus#edit'


# - - - - - - - - - - - - - PAGES

  get 'pages/login'
  get 'pages/sales', to: "pages#sales"
  get 'pages/contact', to: "pages#contact"

# - - - - - - - - - - - - - API ROUTES


 namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :orders, only: [ :index, :show ]
      resources :menus, only: [ :index, :show ]
      resources :menu_categories, only: [ :index, :show ]
      resources :menu_subcategories, only: [ :index, :show ]
      resources :menu_items, only: [:index, :show]
      resources :users, only: [ :index, :show ]
      post 'request', to: "signatures#receive_params"
    end
  end

end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discount.rb
class Discount < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :user, optional: true

  has_many :menu_categories
  has_many :menu_subcategories
  has_many :menu_items

  accepts_nested_attributes_for :menu_items
  validates :name, :description, presence: true
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  belongs_to :menu, optional: true

  has_many :menu_items
  has_many :menu_subcategories
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_subcategory, optional: true
  belongs_to :menu_category, optional: true
  belongs_to :menu, optional: true
  belongs_to :price, optional: true
  belongs_to :user, optional: true


end

app/models/menu_subcategory.rb
class MenuSubcategory < ApplicationRecord
  belongs_to :menu_category, optional: true
  belongs_to :menu, optional: true

  has_many :menu_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_payment, optional: true
  belongs_to :user, optional: true
  belongs_to :order_status, optional: true
  belongs_to :address, optional: true
  belongs_to :phone_number, optional: true

  has_many :ordered_items

end

app/models/order_payment.rb
class OrderPayment < ApplicationRecord
  belongs_to :order, optional: true
  has_one :order_payment

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :menu_item, optional: true
  belongs_to :order, optional: true


end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/payment_status.rb
class PaymentStatus < ApplicationRecord
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :menu_item, optional: true
end

app/models/signature.rb
class Signature < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :menus
  has_many :phone_numbers
  has_many :addresses
  has_many :menu_items
end

app/controllers/api/v1/menus_controller.rb
class Api::V1::MenusController < Api::V1::BaseController
  before_action :set_menu, only: [ :show ]

  def show
  end

  def index
    @menus = Menu.all
    policy_scope(Menu)
  end

  private

  def set_menu
    @menu = Menu.find(params[:id])
    authorize @menu  # For Pundit
  end

end

app/controllers/menus_controller.rb
require 'menu_items_controller'

class MenusController < ApplicationController
  before_action :set_menu, only:[:show, :edit, :update, :get_category, :get_subcategory]

  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  # def item
  #   @item = Item.find(item_params)
  # end

  def create
    @menu = Menu.new(menu_params)
    @menu.save!
  end

  def show
  end

  def edit

    ## Calls private methods to send category names
    ## to view
    @category_names = get_category_names
    @subcategory_names = get_subcategory_names
  end

  def update
    @menu = Menu.find(params[:id])
    @menu.user = current_user

    if @menu.update(menu_params)
      redirect_to menu_path(@menu)
    else
      render :edit
    end

    @items = @menu.menu_items

    # @item = Item.find(params[:id])

    # if @item.update(item_params)
    #   redirect_to menu_path(@menu)
    # else
    #   render :edit
    # end
  end

  private


  ###### GETS CATEGORY AND SUBCATEGORY NAMES
  ###### FOR ADMIN DROPDOWNS
  def get_category_names
     categories = MenuCategory.all
     names = []
     categories.each do |category|
        names << category.name
      end
    @category_names = names
  end

  def get_subcategory_names
     subcategories = MenuSubcategory.all
     names = []
     subcategories.each do |subcategory|
        names << subcategory.name
      end
    @subcategory_names = names
  end

  def get_category
    @category = @menu.menu_category
  end

  def get_subcategory
    @subcategory = @menu.menu_subcategory
  end

  ###########
  ###########

  def set_menu
    @menu = Menu.find(params[:id])
    @menu_items = Menu.find(params[:id]).menu_items
  end

  def menu_params
    params.require(:menu).permit(:name, :description, :time_start, :time_end)
  end

  def item_params
    params.require(:menu_item).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/menus/edit.html.erb
<h1>Menus#edit</h1>
<p>Find me in app/views/menus/edit.html.erb</p>

<div style="padding-left: 30px">
<%= simple_form_for(@menu) do |menu| %>
  <%= menu.input :name, placeholder: "name", label: false %>
  <%= menu.input :description, label: false %>

  <%#= menu.input :menu_categories, :collection => @category_names, input_html: { multiple: true } %>
  <%#= menu.input :menu_subcategories, :collection => @subcategory_names, input_html: { multiple: true } %>

  <%= menu.input :time_start %>
  <%= menu.input :time_end %>
  <%= menu.input :days_available%>
  <%= menu.association :menu_categories, :collection => @category_names%>
   <%#= menu.select :menu_categories, @category_names, {}, class: "form-control" %>


  <%= menu.button :submit, "Update Menu", class: "btn btn-primary"%>
  <%end%>
  <!-- - - - - - menu items test -->
  <%= link_to "Add New Item", new_menu_item_path, class: "btn btn-success" %>
  <h4> Menu Items </h4>
    <% @menu.menu_items.each do |item| %>
      <%= link_to "#{item.name}", edit_menu_item_path(item) %>
      <br>
  <%end%>
</div>

 <!-- RENDER THE MENU ITEM PARTIAL -->



  <!-- - - - - - iterate through menu items -->

app/views/menus/index.html.erb
<h1>Menus#index</h1>
<p>Find me in app/views/menus/index.html.erb</p>

 <%= link_to "Add A New Menu", new_menu_path %>

<div style="background-color: lightgray; width: 500px; margin: 20px; padding: 10px;">
  <% @menus.each do |menu| %>
    <h3><%= menu.name %> </h3>
    <p>Description:<%= menu.description %> </p>
    <%= menu.time_start %>
    <%= menu.time_end %>
    <%= menu.days_available %>

    <%= link_to "View Menu", menu_path(menu.id) %>
  <% end %>



     <%#= link_to "Profile", @menu %>
</div>

app/views/menus/new.html.erb
<h1>Menus#new</h1>
<p>Find me in app/views/menus/new.html.erb</p>

app/views/menus/show.html.erb
<h1>Menus#show</h1>
<p>Find me in app/views/menus/show.html.erb</p>


<div class="menu-card" style="background-color: lightgray; width: 900px; margin: 20px; padding: 10px;">
    <h4> <%= @menu.name %></h4>
    </br>
    <p><%= @menu.description %></p>
      <% @menu.menu_categories.each do |category| %>
        <strong><%= "Menu items in " + category.name + " category" %></strong>
      </br>
        <ul>
            <% category.menu_items.each do |item| %>
              <li>
                <ul><%= item.name %></ul>
                <ul><%= item.price %></ul>
            <% end %>
              </li>
        </ul>
    <% end %>

    <strong><%= link_to "Edit This Menu", edit_menu_path %></strong>

</div>