config/routes.rb
Rails.application.routes.draw do
  get 'menu_categories/index'
  get 'menu_categories/show'
  get 'menu_categories/edit'
  patch 'menu_categories/update'
  get 'menu_categories/delete'



resources :menu_items
  # get 'menu_items/index'
  # get 'menu_items/show'
  # get 'menu_items/edit'
  # get 'menu_items/update'
  # get 'menu_items/delete'

  devise_for :users

  root 'orders#index'

# - - - - - - - - USERS has_many Addresses/Phone Numbers/Orders

  # resources :users, only: [:show, :create, :update, :edit] do
  #   resources :addresses
  #   resources :phone_numbers
  #   resources :orders, only: [:index, :show, :create, :delete]
  # end

  get 'orders/index', to: "orders#index"
  get 'orders/show', to: "orders#show"
  post 'orders/create', to: "orders#create"
  get 'orders/edit', to: "orders#edit"
  get 'orders/delete', to: "orders#delete"



  # patch 'menus/update', to: "menus#update"

resources :menus do
  resources :menu_items
end

  # get 'menus/index' => 'menus'
  # get 'menus/new', to: 'menus#new'
  # post 'menus/create', to:'menus#create'
  # get 'menus/:id', to: 'menus#show'
  # get 'menus/:id/edit', to: 'menus#edit'


# - - - - - - - - - - - - - PAGES

  get 'pages/login'
  get 'pages/sales', to: "pages#sales"
  get 'pages/contact', to: "pages#contact"

# - - - - - - - - - - - - - API ROUTES


 namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :orders, only: [ :index, :show ]
      resources :menus, only: [ :index, :show ]
      resources :menu_categories, only: [ :index, :show ]
      resources :menu_subcategories, only: [ :index, :show ]
      resources :menu_items, only: [:index, :show]
      resources :users, only: [ :index, :show ]
      post 'request', to: "signatures#receive_params"
    end
  end

end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/discount.rb
class Discount < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :user, optional: true

  has_many :menu_categories
  has_many :menu_subcategories
  has_many :menu_items

  accepts_nested_attributes_for :menu_items
  validates :name, :description, presence: true
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  belongs_to :menu, optional: true

  has_many :menu_items
  has_many :menu_subcategories
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_subcategory, optional: true
  belongs_to :menu_category, optional: true
  belongs_to :menu, optional: true
  belongs_to :price, optional: true
  belongs_to :user, optional: true


end

app/models/menu_subcategory.rb
class MenuSubcategory < ApplicationRecord
  belongs_to :menu_category, optional: true
  belongs_to :menu, optional: true

  has_many :menu_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_payment, optional: true
  belongs_to :user, optional: true
  belongs_to :order_status, optional: true
  belongs_to :address, optional: true
  belongs_to :phone_number, optional: true

  has_many :ordered_items

end

app/models/order_payment.rb
class OrderPayment < ApplicationRecord
  belongs_to :order, optional: true
  has_one :order_payment

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :menu_item, optional: true
  belongs_to :order, optional: true


end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/payment_status.rb
class PaymentStatus < ApplicationRecord
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :menu_item, optional: true
end

app/models/signature.rb
class Signature < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :menus
  has_many :phone_numbers
  has_many :addresses
  has_many :menu_items
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunchesApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= render "shared/flashes" %>

    <%= yield %>

  </body>

  <script type="text/javascript" src="js/jquery-1.8.0.js"></script>
  <script type="text/javascript" src="js/bootstrap.min.js"></script>

</html>

app/views/pages/login.html.erb
<h1>Pages#login</h1>
<p>Find me in app/views/pages/login.html.erb</p>

app/views/shared/_flashes.html.erb
    <% if notice %>
      <p class="alert alert-success flash"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger flash"><%= alert %></p>
    <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logoblackonwhite.svg", class: "navbar-logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Orders", orders_index_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Menus", menus_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sales", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "munchicon.svg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Orders", orders_index_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Menus", menus_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Sales", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
       <!--  <li><a href="#">Orders</a></li>
        <li><a href="#">Menus</a></li>
        <li><a href="#">Sales</a></li> -->
      </ul>
    </div>
  </div>
</div>